name: CaseTracker - Automation Deployment

on:
  push:
    branches:
      - automation
      - 976-office-details-page-analytics-automation-testing
      - 992-case-detail-page---treatment-section---automation
      - 991-appointment-type---automation
      - 989-task-page---automation
      - 1032-endundo-treatment-and-for-group-office

  schedule:
    # This cron expression will run the tests daily at 2 AM UTC
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin/

      - name: Run Cucumber Tests
        run: |
          cd case-tracker-automation
          echo "Current directory: $(basename \"$(pwd)\")"
          mvn clean test 2>&1 | grep -i "error\|failed\|exception"

#      - name: Commit and Push the Report
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          # Navigate to the test report directory
#          cd case-tracker-automation/test-output/SparkReport
#          # Configure git user for actions
#          git config --global user.name "github-actions[bot]"
#          git config --global user.email "github-actions[bot]@users.noreply.github.com"
#          # Add and commit the updated Spark.html
#          git add Spark.html
#          git commit -m "Update test report [CI]"
#          # Push changes to the repository
#          git push origin automation